In [1]:
import torch

In [5]:
data = [1, 2, 3, 4]
tensor = torch.tensor(data) 
print(tensor)

tensor([1, 2, 3, 4])


In [7]:
zeros_tensor = torch.zeros(2, 3) 
print(zeros_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [9]:
ones_tensor = torch.ones(2, 3) 
print(ones_tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [11]:
rand_tensor = torch.rand(3, 3)
print(rand_tensor)

tensor([[0.8500, 0.5538, 0.5677],
        [0.1693, 0.4645, 0.3494],
        [0.5969, 0.7339, 0.9124]])


In [13]:
randn_tensor = torch.randn(2, 3)
print(randn_tensor)

tensor([[-0.3814, -0.3696, -0.8462],
        [ 0.4521, -0.4258, -1.0446]])


In [15]:
linspace_tensor = torch.linspace(0, 10, steps=5) 
print(linspace_tensor)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])


In [17]:
arange_tensor = torch.arange(0, 10, step=2) 
print(arange_tensor)

tensor([0, 2, 4, 6, 8])


In [19]:
eye_tensor = torch.eye(3) 
print(eye_tensor)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [21]:
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[5, 6], [7, 8]])

matmul_result = torch.matmul(tensor1, tensor2)
print(matmul_result)

In [25]:
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[5, 6], [7, 8]])

mm_result = torch.mm(tensor1, tensor2)
print(mm_result)

In [31]:
tensor1 = torch.randn(10, 3, 4)

tensor2 = torch.randn(10, 4, 5)

bmm_result = torch.bmm(tensor1, tensor2) 

print(bmm_result.size()) 

torch.Size([10, 3, 5])


In [33]:
tensor1 = torch.tensor([[1, 2], [3, 4]])

tensor2 = torch.tensor([[5, 6]])

cat_result = torch.cat((tensor1, tensor2), dim=0)

print(cat_result)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [35]:
tensor1 = torch.tensor([1, 2])

tensor2 = torch.tensor([3, 4])

stack_result = torch.stack((tensor1, tensor2), dim=0)

print(stack_result)

tensor([[1, 2],
        [3, 4]])


In [39]:
tensor = torch.tensor([1, 2, 3, 4, 5, 6])


# Split into three chunks

split_result = torch.split(tensor, 2)

for chunk in split_result:

      print(chunk)

tensor([1, 2])
tensor([3, 4])
tensor([5, 6])


In [41]:
tensor = torch.tensor([1, 2, 3, 4, 5, 6])

chunk_result = torch.chunk(tensor, 3) 

for chunk in chunk_result:
        print(chunk)

tensor([1, 2])
tensor([3, 4])
tensor([5, 6])


In [43]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

reshape_result = torch.reshape(tensor, (3, 2)) 
print(reshape_result)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [45]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

view_result = tensor.view(3, 2) 
print(view_result)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [47]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

transpose_result = torch.transpose(tensor, 0, 1)

print(transpose_result)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [49]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
t_result = torch.t(tensor)
print(t_result)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [51]:
tensor = torch.tensor([1, 2, 3, 4])
unsqueeze_result = torch.unsqueeze(tensor, dim=0) 
print(unsqueeze_result)

tensor([[1, 2, 3, 4]])


In [53]:
tensor = torch.tensor([[[1, 2, 3, 4]]])

squeeze_result = torch.squeeze(tensor) 
print(squeeze_result)

tensor([1, 2, 3, 4])


In [55]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

flatten_result = torch.flatten(tensor)

print(flatten_result)

tensor([1, 2, 3, 4, 5, 6])


In [57]:
tensor = torch.tensor([1, 2, 3, 4], dtype=torch.float32)

norm_result = torch.norm(tensor) 
print(norm_result)

tensor(5.4772)


In [59]:
tensor = torch.tensor([[1, 2], [3, 4]])

max_result = torch.max(tensor)

print(max_result)

tensor(4)


In [61]:
tensor = torch.tensor([[1, 2], [3, 4]])

min_result = torch.min(tensor)

print(min_result)

tensor(1)


In [63]:
tensor = torch.tensor([[1, 2], [3, 4]])

sum_result = torch.sum(tensor) 
print(sum_result)

tensor(10)


In [65]:
tensor = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)

mean_result = torch.mean(tensor) 
print(mean_result)

tensor(2.5000)


In [67]:
tensor = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)

std_result = torch.std(tensor) 
print(std_result)

tensor(1.2910)


In [69]:
tensor = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)

var_result = torch.var(tensor) 
print(var_result)

tensor(1.6667)


In [71]:
tensor = torch.tensor([[1, 2], [3, 4]])

argmax_result = torch.argmax(tensor) 
print(argmax_result)

tensor(3)


In [73]:
tensor = torch.tensor([[1, 2], [3, 4]])

argmin_result = torch.argmin(tensor) 
print(argmin_result)

tensor(0)


In [75]:
import torch.nn as nn

In [79]:
linear = nn.Linear(in_features=2, out_features=3)

input_tensor = torch.tensor([[1.0, 2.0]])
output_tensor = linear(input_tensor) 
print(output_tensor)

tensor([[-0.5587,  0.2314, -0.4909]], grad_fn=<AddmmBackward0>)


In [81]:
conv2d = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3)

input_tensor = torch.randn(1, 1, 5, 5)
output_tensor = conv2d(input_tensor) 

print(output_tensor.size())

torch.Size([1, 1, 3, 3])


In [83]:
relu = nn.ReLU()

input_tensor = torch.tensor([-1.0, 0.0, 1.0])
output_tensor = relu(input_tensor) 

print(output_tensor)

tensor([0., 0., 1.])


In [85]:
sigmoid = nn.Sigmoid()

input_tensor = torch.tensor([-1.0, 0.0, 1.0])
output_tensor = sigmoid(input_tensor) 

print(output_tensor)

tensor([0.2689, 0.5000, 0.7311])


In [87]:
loss_fn = nn.CrossEntropyLoss()

inputs = torch.tensor([[0.5, 1.5, 2.0]]) 
targets = torch.tensor([2])

loss = loss_fn(inputs, targets)

print(loss)

tensor(0.6041)


In [89]:
loss_fn = nn.MSELoss()

inputs = torch.tensor([0.5, 1.5, 2.0]) 
targets = torch.tensor([1.0, 2.0, 3.0])

loss = loss_fn(inputs, targets)

print(loss)

tensor(0.5000)


In [91]:
import torch.optim as optim

In [93]:
model = nn.Linear(in_features=2, out_features=1)

optimizer = optim.SGD(model.parameters(), lr=0.01)

input_tensor = torch.tensor([[1.0, 2.0]])
target = torch.tensor([[1.0]])

output = model(input_tensor)

loss = nn.MSELoss()(output, target)

optimizer.zero_grad() 
loss.backward() 
optimizer.step()

print(output)

tensor([[0.6546]], grad_fn=<AddmmBackward0>)


In [95]:
model = nn.Linear(in_features=2, out_features=1)

optimizer = optim.Adam(model.parameters(), lr=0.01)

input_tensor = torch.tensor([[1.0, 2.0]]) 
target = torch.tensor([[1.0]])

output = model(input_tensor)

loss = nn.MSELoss()(output, target)

optimizer.zero_grad() 
loss.backward() 
optimizer.step()

print(output)

tensor([[0.3785]], grad_fn=<AddmmBackward0>)


In [97]:
model = nn.Linear(in_features=2, out_features=1)

optimizer = optim.Adam(model.parameters(), lr=0.01)

scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=10, gamma=0.1)

input_tensor = torch.tensor([[1.0, 2.0]]) 
target = torch.tensor([[1.0]])

for epoch in range(20):
    output = model(input_tensor)
    loss = nn.MSELoss()(output, target)
    optimizer.zero_grad() 
    loss.backward() 
    optimizer.step()

    scheduler.step()

    print(f"Epoch {epoch+1}, Loss: {loss.item()}, LR: {scheduler.get_last_lr()}")

Epoch 1, Loss: 2.515454053878784, LR: [0.01]
Epoch 2, Loss: 2.3901727199554443, LR: [0.01]
Epoch 3, Loss: 2.268181085586548, LR: [0.01]
Epoch 4, Loss: 2.149533748626709, LR: [0.01]
Epoch 5, Loss: 2.0342812538146973, LR: [0.01]
Epoch 6, Loss: 1.922466516494751, LR: [0.01]
Epoch 7, Loss: 1.8141309022903442, LR: [0.01]
Epoch 8, Loss: 1.7093075513839722, LR: [0.01]
Epoch 9, Loss: 1.6080241203308105, LR: [0.01]
Epoch 10, Loss: 1.510303258895874, LR: [0.001]
Epoch 11, Loss: 1.416159987449646, LR: [0.001]
Epoch 12, Loss: 1.4069697856903076, LR: [0.001]
Epoch 13, Loss: 1.3978557586669922, LR: [0.001]
Epoch 14, Loss: 1.3888095617294312, LR: [0.001]
Epoch 15, Loss: 1.3798246383666992, LR: [0.001]
Epoch 16, Loss: 1.3708951473236084, LR: [0.001]
Epoch 17, Loss: 1.3620173931121826, LR: [0.001]
Epoch 18, Loss: 1.353187918663025, LR: [0.001]
Epoch 19, Loss: 1.3444037437438965, LR: [0.001]
Epoch 20, Loss: 1.3356633186340332, LR: [0.0001]


In [99]:
x = torch.tensor(2.0, requires_grad=True) 
y = x ** 2

grad = torch.autograd.grad(outputs=y, inputs=x)
print(grad)

(tensor(4.),)


In [101]:
x = torch.tensor(2.0, requires_grad=True) 
y = x ** 2

y.backward()

print(x.grad)

tensor(4.)


In [103]:
cuda_available = torch.cuda.is_available()

print(cuda_available)

False


In [107]:
if torch.cuda.is_available():
    with torch.cuda.device(0):
# Create a tensor and move it to the GPU
       tensor = torch.tensor([1, 2, 3], device=torch.device('cuda'))
       print(tensor)

In [109]:
tensor = torch.tensor([1, 2, 3])
torch.save(tensor, 'tensor.pth')

In [111]:
tensor = torch.load('tensor.pth') 
print(tensor)

tensor([1, 2, 3])


C:\Users\User\AppData\Local\Temp\ipykernel_15620\1987365928.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  tensor = torch.load('tensor.pth')


In [117]:
class SimpleNN(nn.Module):

      def __init__(self): 
          super(SimpleNN, self).__init__() 
          self.fc1 = nn.Linear(2, 2) 
          self.fc2 = nn.Linear(2, 1)

      def forward(self, x):
          x	= self.fc1(x)
          x	= torch.relu(x)
          x	= self.fc2(x) 
          
          return x
          
model = SimpleNN() 
print(model)

SimpleNN(
  (fc1): Linear(in_features=2, out_features=2, bias=True)
  (fc2): Linear(in_features=2, out_features=1, bias=True)
)


In [119]:
model = nn.Sequential(
        nn.Linear(2, 2), nn.ReLU(), nn.Linear(2, 1)
       )

print(model)

Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): ReLU()
  (2): Linear(in_features=2, out_features=1, bias=True)
)


In [121]:
dropout = nn.Dropout(p=0.5)

input_tensor = torch.randn(2, 3)
output_tensor = dropout(input_tensor)

print(output_tensor)

tensor([[ 2.7138, -0.9640,  2.7560],
        [ 0.0000,  0.5864,  0.0000]])


In [123]:
batch_norm = nn.BatchNorm2d(num_features=3)

input_tensor = torch.randn(2, 3, 4, 4)
output_tensor = batch_norm(input_tensor)

print(output_tensor)

tensor([[[[-0.1852,  0.3328, -1.7205, -0.0040],
          [-1.3741, -0.5249,  0.5749, -0.9485],
          [ 0.6455,  2.5908, -0.1493, -0.3556],
          [ 1.2155, -0.6411,  1.2372, -0.3352]],

         [[ 0.8375,  1.2993, -0.9723, -2.6958],
          [ 0.2791, -1.7267,  0.6025,  0.7566],
          [-0.6430, -0.2880,  0.3019, -0.0993],
          [ 1.3650,  1.3244,  1.2191,  0.3596]],

         [[ 0.6427, -0.4442,  0.2860,  0.2954],
          [ 0.4988,  0.7148, -1.3696, -0.5979],
          [-0.5079,  1.3890, -0.0206, -1.0262],
          [-0.1856, -1.1410, -0.4332, -0.7846]]],


        [[[ 0.2925, -2.0520, -0.2209,  1.0290],
          [ 0.9717, -0.9777, -1.4887,  0.0330],
          [ 0.0597,  1.1173, -0.6246, -0.3798],
          [-0.8849,  0.7958,  1.0975,  0.8737]],

         [[-0.2374, -0.1053,  1.3717,  0.2321],
          [-0.0517,  0.4391,  0.4906, -0.3165],
          [-0.0792, -2.3529, -0.5814, -1.0641],
          [ 1.1402, -0.4793, -0.6306,  0.3048]],

         [[ 1.0824,  2.0588,

In [125]:
import torch
from torch.utils.data import DataLoader, TensorDataset

In [127]:
data = torch.randn(100, 2) 
targets = torch.randn(100, 1)
dataset = TensorDataset(data, targets)

data_loader = DataLoader(dataset, batch_size=10, shuffle=True)

for batch_data, batch_targets in data_loader:
          print(batch_data.size(), batch_targets.size())

torch.Size([10, 2]) torch.Size([10, 1])
torch.Size([10, 2]) torch.Size([10, 1])
torch.Size([10, 2]) torch.Size([10, 1])
torch.Size([10, 2]) torch.Size([10, 1])
torch.Size([10, 2]) torch.Size([10, 1])
torch.Size([10, 2]) torch.Size([10, 1])
torch.Size([10, 2]) torch.Size([10, 1])
torch.Size([10, 2]) torch.Size([10, 1])
torch.Size([10, 2]) torch.Size([10, 1])
torch.Size([10, 2]) torch.Size([10, 1])


In [129]:
import torch
from torch.utils.data import Dataset

In [136]:
class CustomDataset(Dataset):

    def __init__(self, data, targets): 
        self.data = data 
        self.targets = targets

    def __len__(self):
       return len(self.data)

    def __getitem__(self, index):
       return self.data[index], self.targets[index]

data = torch.randn(100, 2)
targets = torch.randn(100, 1)
dataset = CustomDataset(data, targets)

In [138]:
print(len(dataset))

100


In [140]:
print(dataset[0])

(tensor([-0.6967, -0.1066]), tensor([0.2474]))
